### ISSUE TITLE
Insights SSID variable 1st letter uppercase

### ISSUE THREAD

**Issue by JohnMacrae** [espressif/esp-insights#1]
Thanks for this functionality!

Using the switch example code and with variable and metrics enabled, I noticed that the SSID is reported with the 1st letter in uppercase.

in this case the ssid is
![Screenshot (167)](https://user-images.githubusercontent.com/13579277/124767864-16ddf000-df30-11eb-96fc-72e8f1254f70.png)
![Screenshot (168)](https://user-images.githubusercontent.com/13579277/124767869-17768680-df30-11eb-898f-0e2844bc2113.png)

**Comment by shubhamdp** [comment]
Hi @JohnMacrae this issue was fixed earlier today and you should be able to see the SSID as it is.

**Comment by JohnMacrae** [comment]
thanks @shubhamdp - it may be that it has not been pushed since I installed the Insights only a few hours ago and there is no sign of anything new in the repo for the last few days.
