### ISSUE TITLE
Is it free to use?

### ISSUE THREAD

**Issue by HoGC** [espressif/esp-insights#13]
Is it free to use?

**Comment by adwait-esp** [comment]
Yes, you can try it for free. We have ESP Insights Dashboard deployed as a service, where you can signup, and login to check all the diagnostics information remotely via web browser.

**Comment by HoGC** [comment]
So in the future it will be a paid service，Can individual developers have several free keys?

**Comment by adwait-esp** [comment]
It would be a paid service in future for commercial use. Plan is to maintain it free for individual developers with some monthly usage limits may be.

**Comment by connornishijima** [comment]
Has this changed at all?
