### ISSUE TITLE
"Please provide a valid package name"

### ISSUE THREAD

**Issue by ivancmz** [espressif/esp-insights#17]
When trying to add the Firmware Package on the dashboard I get the "Please provide a valid package name" error.

![Captura de pantalla 2022-11-29 213231](https://user-images.githubusercontent.com/594108/204641869-3e376812-9da0-40ee-8ac3-27cc37351827.png)

The Project name is: R84.24 
The version is:  2_0_0_221118
The zip file generated is: R84.24-v2_0_0_221118.zip
The package name I'm using is: R84.24-v2_0_0_221118, also tried R84.24-2_0_0_221118 and other combinations.

![Captura de pantalla 2022-11-29 213313](https://user-images.githubusercontent.com/594108/204641910-15d268a5-ee44-4fd5-951d-deb91531386d.png)

**Comment by ivancmz** [comment]
Changed version to a more "traditional" scheme (i.e., R84.24-2.0), same issue.

Changed project name to R84_24 to avoid dots (i.e., R84_24-2.0), same issue (R84_24-2.0).

Changed project name to Light to match exactly the dialogs example values (Light-2.0) and it still fails.

![image](https://user-images.githubusercontent.com/594108/204741610-cbbf096a-0c45-4c70-bb81-0e2b1b88c9f7.png)

**Comment by ivancmz** [comment]
It finally worked after removing the version part, that is package name "Light" without the "-2.0"

**Comment by shahpiyushv** [comment]
@ivancmz , good to know you could get it working but we do understand that this is very inconvenient. The package name can actually be any friendly name that the user wants, independent of actual project name and version. We will fix this bug asap.

**Comment by ivancmz** [comment]
> @ivancmz , good to know you could get it working but we do understand that this is very inconvenient. The package name can actually be any friendly name that the user wants, independent of actual project name and version. We will fix this bug asap.

Thanks @shahpiyushv. What I've seen is that it only allows letters in the name, no numbers or special characters like underscore. I see now that I can use any name, but since the placeholder example was "Light-2.0" I assumed it had to match the project name and version.

**Comment by adwait-esp** [comment]
This issue was caused by some regression, it has been fixed and pushed to production. @ivancmz can you please check and close if the issue is fixed?
