### ISSUE TITLE
Add esp-insights to component manager

### ISSUE THREAD

**Issue by ivancmz** [espressif/esp-insights#18]
To test esp_insights in an existing project I had to clone the repository and copy the components folder into my project's component folder and then enable it using idf.py menuconfig. Not sure if there's an easier way of doing this, but using the component manager would be a nice way of simplifying the process.

**Comment by antoniuschan99** [comment]
It's in component manager now! https://components.espressif.com/components/espressif/esp_insights

**Comment by ivancmz** [comment]
This is awesome!! Thanks!! I'll try it right now!!
