### ISSUE TITLE
Issues regarding migrating ESP-Insights from idf-V4.4 to idf-V5.0

### ISSUE THREAD

**Issue by Munjalnyk** [espressif/esp-insights#22]
there are errors with deprecated file name for eg. sntp.h has been upgraded as esp_sntp.h and there many more file names such that. Anyone has figured it out or process is still in development. can some one provide migrating guide??

**Comment by vikramdattu** [comment]
Hi @yorocoboy1 thanks for reporting. We will take a look and fix this. Deprecation, however, should be treated as warning and not error. Please check if you are adding stricter compiler flags, `-Werror=deprecated-declarations` in this case.

**Comment by vikramdattu** [comment]
cc @sanketwadekar

**Comment by shahpiyushv** [comment]
This should have been sorted by now. Closing this.
