### ISSUE TITLE
Can't get crash stack info.

### ISSUE THREAD

**Issue by ftc300** [espressif/esp-insights#26]
I get the tip below.
> We could not find the firmware image to cross-rererence this log entry. Please upload a firmware image to get cross-referenced information for this log entry.

<img width="952" alt="image" src="https://github.com/espressif/esp-insights/assets/12816061/7dd64cc5-10fe-4100-9728-98b6438db66a">
I get err infomation,then i try to upload my *.bin file .But this file is gray,i can't select it.
<img width="944" alt="image" src="https://github.com/espressif/esp-insights/assets/12816061/61d51dfc-a343-4f33-8c64-25f7f3cb7c41">
PS: I use  ”idf.py build “ cmd to create *.bin.

**Comment by vikramdattu** [comment]
Hello @ftc300 ESP-Insights creates a package for you which contains a `.elf` file of the build which exactly needs to match to the firmware Insights were collected for.

Please read more about this [here](https://github.com/espressif/esp-insights/tree/main/examples/minimal_diagnostics#upload-the-firmware-package).
