### ISSUE TITLE
Unable to delete firmware package

### ISSUE THREAD

**Issue by tmedicci** [espressif/esp-insights#5]
I couldn't delete old firmware packages by clicking on the  #"Delete" button on [Firmware Packages tab](https://dashboard.insights.espressif.com/home/firmware-packages).

![image](https://user-images.githubusercontent.com/28811720/153758345-20bf03dd-241a-4ecc-95bb-3b2fe052a9ae.png)

**Comment by adwait-esp** [comment]
We have fixed the delete package failure issue and our deployed services are updated with the latest code changes. 

@tmedicci  can you please try dashboard.insights.espressif.com and check if you can delete any existing package now?

**Comment by tmedicci** [comment]
Yes! It seems to be fixed. I can delete existing packages now. Thanks!
