### ISSUE TITLE
Unable to upload firmware package

### ISSUE THREAD

**Issue by tmedicci** [espressif/esp-insights#6]
Sometimes it's difficult to upload a new firmware package. Most of the time it says "Something went wrong" without uploading the firmware properly. However, it seems that the firmware is uploaded besides the error message.

![Screenshot from 2022-02-13 11-57-13](https://user-images.githubusercontent.com/28811720/153759624-99c83888-8b5b-484a-abe5-6d5ea7f06247.png)

**Comment by adwait-esp** [comment]
Is this issue intermittent? Able to upload the firmware package. Will keep a tab on this, we have raised an issue for the same.

**Comment by tmedicci** [comment]
In fact, it's very frequent... I'd say that is more probably to show the error popup (even if the firmware is uploaded, by checking the uploaded firmware list) than showing a message that the firmware was uploaded successfully.

This screenshot, however, showed a moment that the firmware did not appear in the firmware list.

**Comment by adwait-esp** [comment]
We have fixed the intermittent package upload failure issue and our deployed services are updated with the latest code changes. 

@tmedicci  can you please try dashboard.insights.espressif.com and check if you can upload your package now?

**Comment by tmedicci** [comment]
Yes! I could upload the same package that failed before. Thanks!
