### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by FanhuaCloud** [espressif/esp-insights#7]
C:/Users/he/Desktop/esp-insights/components/esp_diagnostics/src/esp_diagnostics_utils.c: In function 'esp_diag_task_snapshot_get$part$0':
C:/Users/he/Desktop/esp-insights/components/esp_diagnostics/src/esp_diagnostics_utils.c:156:13: error: 'strncpy' output truncated before terminating nul copying as many bytes from a string as its length [-Werror=stringop-truncation]
             strncpy(tasks[i].name, name, strlen(name));
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by shubhamdp** [comment]
@FanhuaCloud thanks for putting up an issue, we'll release a fix sooner.

**Comment by shubhamdp** [comment]
@FanhuaCloud [b53081cc0a362482f31584ed34fdde8db38220ef](https://github.com/espressif/esp-insights/commit/35457d230203ed21a37f29021dd542f1dc6ad0a9) will fix this issue. Can you please pull in the latest changes and try again.

**Comment by FanhuaCloud** [comment]
> 

thanks, i will test it

**Comment by FanhuaCloud** [comment]
> @FanhuaCloud [b53081cc0a362482f31584ed34fdde8db38220ef](https://github.com/espressif/esp-insights/commit/35457d230203ed21a37f29021dd542f1dc6ad0a9) will fix this issue. Can you please pull in the latest changes and try again.

thanks, i will test it

**Comment by shubhamdp** [comment]
@FanhuaCloud If this is working for you can you please close this issue.
